### PR TITLE
okhttp3 3.4.1 had a bug which was fixed in 3.4.2

### PR DESCRIPTION
**Pull request by xiaodong-xie**
See: https://github.com/square/okhttp/issues/2756

### CODE REVIEW

**Comment by xiaodong-xie** [comment]
Ping @atpaino? Thanks.

**Comment by quanpod** [comment]
Hi @xiaodong-xie - acknowledging the pull request, thanks! We'll have our team look at it and review in an upcoming sprint. (You can ping me in the future)

**Comment by ehrmann** [comment]
The change looks good. We'll plan the next release in an upcoming sprint. In the interim, if you're affected by the `okhttp` bug, you can around it by pinning `okhttp` to the new version, e.g.

Maven:
```
<dependencyManagement>
    <dependencies>
        ...
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>3.4.2</version>
        </dependency>
    </dependencies>
</dependencyManagement>
```

Gradle:
```
dependencies {
    ...
    implementation('com.squareup.okhttp3:okhttp:3.4.2') {
        force = true
    }
}
```

**Comment by xiaodong-xie** [comment]
Thanks for merging, @ehrmann 😄

**Pull request merged**
